---

- include_vars: "{{ansible_os_family}}.yml"

- name: Add duplicity repository
  apt_repository:
    repo: ppa:duplicity-team/ppa
    update_cache: yes
  when: backup_duplicity_ppa

- name: Install dependencies
  apt: name={{item}}
  with_items:
  - cron
  - gzip
  - python-boto
  - s3cmd

- set_fact: backup_duplicity_pkg="{{backup_duplicity_pkg}}={{backup_duplicity_version}}"
  when: backup_duplicity_version

- name: Install duplicity
  apt: pkg={{backup_duplicity_pkg}}
